version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8081:80"  # Cambia 8080 al puerto que prefieras
    volumes:
      - ./src:/var/www/html
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
